#!/usr/bin/bash

declare bat_0_level=$(cat /sys/class/power_supply/BAT0/capacity)
# declare bat_1_level=$(cat /sys/class/power_supply/BAT1/capacity)
declare message=$(printf "Battery Level: %s%%" "$bat_0_level")

dunstify "Battery Status" "$message" -h string:x-dunst-stack-tag:peachbatstatus
