#!/bin/bash

# =========================
# CR :: Composer Require
# -------------------------
#  Search for a term in available composer packages.
#  Then install selected one as a REQUIRE dependancy.
# ----------------------------------------------------

if [[ -z $1 ]]
then
    echo "Please use a search term to search for a composer package."
    exit 1
fi

USING_SAIL=false
if [[ -x ./vendor/bin/sail ]]
then
    USING_SAIL=true
fi

if [[ $USING_SAIL = true ]]
then
    option=$(./vendor/bin/sail composer search "$1" | fzf | awk '{print $1}') 
else
    option=$(composer search "$1" | fzf | awk '{print $1}') 
fi

if [[ -z "$option" ]]
then
    echo "Exiting"
    exit 1
fi


if [[ $USING_SAIL = true ]]
then
    ./vendor/bin/sail composer require "$option"
else
    composer require "$option"
fi
