#!/usr/bin/bash

# Description: Display currently playing media track using playerctl.
# Usage: currently-playing
# Dependencies: playerctl

title=$(playerctl metadata title)
artist=$(playerctl metadata artist)
status=$(playerctl status)

echo "  $status: $title by $artist"
