#!/usr/bin/bash

BROWSER_CMD="firefox -P"

declare -a profiles=(
    "Amazon - amazon"
    "DuckDuckGo - duckduckgo"
    "Facebook - facebook"
    "Github - github"
    "Google - google"
    "LinkedIn - linkedin"
    "Pinterest - pinterest"
    "Pocketsmith - pocketsmith"
    "Proton - proton"
    "Quarto - quarto"
    "Reddit - reddit"
    "Twitter - twitter"
    "Work - work"
)

chosen=$(printf '%s\n' "${profiles[@]}" | dmenu -i -l 10 -p 'Firefox Profile: ')

if [[ -z "$chosen" ]]
then
    dunstify "Firefox profile not opened"
    exit 1
fi

chosen_profile=$(printf '%s\n' "$chosen" | awk '{print $3}')
$BROWSER_CMD "$chosen_profile"
