#!/usr/bin/bash

BROWSER_CMD="firefox -P"

declare -a profiles=(
    "amazon"
    "duckduckgo"
    "facebook"
    "github"
    "google"
    "linkedin"
    "music"
    "pinterest"
    "pocketsmith"
    "proton"
    "quarto"
    "reddit"
    "twitter"
    "work"
)

chosen=$(printf '%s\n' "${profiles[@]}" | kickoff --from-stdin --stdout )

if [[ -z "$chosen" ]]
then
    dunstify "Firefox profile not opened"
    exit 1
fi

$BROWSER_CMD "$chosen"
