#!/usr/bin/bash

datetime=$(date +"%Y-%m-%d-%H-%M-%S")

declare paths=(
  "$HOME/Zet"
  "$HOME/.keys"
  "$HOME/.task"
)

for path in "${paths[@]}"
do
  name=$(basename "$path")
  tar cvzf "$HOME"/backups/"$name"-"$datetime".tar.gz "$path"
  s3cmd -e put "$HOME"/backups/"$name"-"$datetime".tar.gz s3://rainbird/"$name"/
done


