#!/usr/bin/bash

if ! command -v git &> /dev/null
then
    echo "Git could not be found."
    exit
fi

if ! command -v fzf &> /dev/null
then
    echo "Fzf could not be found."
    exit
fi

in_bare_root=false

if [[ ! $(git rev-parse --show-toplevel &> /dev/null) ]]
then
    if [[ ! $(git rev-parse --is-bare-repository 2> /dev/null) ]]
    then
        dunstify "Not a git worktree repo"
        exit 1
    fi

    in_bare_root=true
fi

if [[ $in_bare_root == false ]]
then
    pushd "$(git rev-parse --show-toplevel)/.." &> /dev/null || exit
fi

if [[ $(git rev-parse --is-bare-repository) == true ]]
then
    existing_branches=$(git for-each-ref --format='%(refname:short)' refs/heads/)
    new_branch_option="NEW"
    all_options=$(printf '%s\n%s' "$existing_branches" "$new_branch_option")
    chosen=$(echo "$all_options" | fzf)

    if [[ -z "$chosen" ]]
    then
        dunstify "Git worktree branch switch abandoned"
        exit 1
    fi

    if [[ "$chosen" == "NEW" ]]
    then
        read -r -p "New branch name: " chosen
        chosen="${chosen// /-}"
    fi

    worktrees_folder="${chosen##*/}"

    if [[ ! -d "$PWD/worktrees/$worktrees_folder" ]]
    then
        git worktree add "$chosen" &> /dev/null
    fi

    pushd "$PWD/worktrees/$worktrees_folder" &> /dev/null || exit
    new_branch_directory=$(cat ./gitdir)
    echo "${new_branch_directory%%'/.git'}"
    exit 0
fi

dunstify "Not a git worktree repo"
exit 1
