#!/usr/bin/bash

# Description: Fuzzy find and checkout a git branch.
# Usage: gch
# Dependencies: git, fzf, dunstify

set -e

branch=$(git branch | fzf)

if [[ -z "$branch" ]]; then
	echo "Empty"
	exit 0
fi

branch="${branch//[[:space:]]/}"

branch="${branch##\*}"

git checkout "$branch"

dunstify "Git branch" "switched to $branch"
