#!/usr/bin/bash

JIRA_BIN=$HOME/.local/bin/jira

declare -a commands=(checkout)

if [[ -n $COMP_LINE ]]; then
	for c in "${commands[@]}"; do
		[[ ${c:0:${#2}} == "${2,,}" ]] && echo "$c"
	done
	exit
fi

_checkout() {
  select project in WEBSITE DS
  do
    echo "Selected project: $project"
    echo "Selected number: $REPLY"
    break
  done

  chosen_issue=$($JIRA_BIN issue list --assignee=david.peach@getlaidbeds.co.uk -s~"TO DO" -p=$project --plain --no-headers | fzf --reverse | awk '{print $2}')
  touch ~/work/.status/current-issue
  echo "$chosen_issue" > ~/work/.status/current-issue
  dunstify "Jira Issue" "Set to $chosen_issue"
}

_issue() {
  echo "ISSUE"
  # $JIRA_BIN issue view
}

declare CMD="$1"
shift
for c in "${commands[@]}"; do
	[[ $c == "$CMD" ]] && "_$c" "$@" && exit $?
done
