#!/usr/bin/bash

# Description: Output a provided string as a prefix to each line of stdin.
# Usage: <command> | prefix <string>
# Dependencies: bash

declare prefix
declare value
value="$1"

prefix="${value:=}"

while IFS= read -r line;do
  echo "$prefix $line"
done
