#!/usr/bin/bash

issueId=$(gh issue list --state=closed | fzf | awk '{print $1}')

if [[ -z $issueId ]]; then
  echo "No issue chosen" && exit 1
fi

gh issue reopen "$issueId"

echo "Issue $issueId reopened."
