#!/usr/bin/bash

set -e

# Styles imported from ./.local/bin/read_styles
style_heading="\033[36;1;210m"
style_subheading="\033[32;1m"
style_clear="\033[0m"

echo -e "${style_subheading} No longer needed. Kept in dotfiles just in case.${style_clear}"
exit 0

connected=$(sudo wg show)

if [[ -z $connected ]]; then
    sudo wg-quick up work
    notify-send "WireGuard Connected."
else
    sudo wg-quick down work
    notify-send "WireGuard disconnected."
fi

