#!/usr/bin/bash

set -e

# Source common styles
source "$(dirname "$0")/read_styles"

echo -e "${style_subheading} No longer needed. Kept in dotfiles just in case.${style_clear}"
exit 0

connected=$(sudo wg show)

if [[ -z $connected ]]; then
    sudo wg-quick up work
    notify-send "WireGuard Connected."
else
    sudo wg-quick down work
    notify-send "WireGuard disconnected."
fi

