#!/usr/bin/bash

[[ -z "$ZETROOT" ]] && echo "Please set the root directory of zet with the $ZETROOT env." && exit 1;

declare directory="$ZETROOT"

_new() {
	read -r -p $'\e[33mZet title\e[0m: ' title

	filepath="$directory/$title.md"
	mkdir -p "$(dirname "$filepath")"
	touch "$filepath"

	twindow "$filepath" "" "$EDITOR -c 'normal! Gi' '$filepath'" "open"
}

_new
