#!/usr/bin/bash

declare -a commands=(new latest edit)
declare directory="$ZETROOT"

if [[ -n $COMP_LINE ]]; then
  for c in "${commands[@]}"; do
    [[ ${c:0:${#2}} == "${2,,}" ]] && echo "$c"
  done
  exit
fi

_edit() {
  latest=$(find * -maxdepth 1 ! -name '*[!0-9]*' -type d -printf '%p\n' | sort -t '\0' -n | awk -F '\0' '{print $1}' | tail -n1)
  filename="$1"
  if [[ -z $filename ]]; then
    filename="$latest"
  fi
  filepath="$directory/$filename/README.md"

  twindow "$filepath" "" "$EDITOR -c 'normal! G' $filepath" "open"
}

_latest() {
  while read -r filename; do
    file="$directory/$filename/README.md"
    titleline=$(head -1 "$file")
    title="${titleline//# /}"
    echo -e " \033[31;1;210m$filename\033[0m \033[96;2m$title\033[0m"
  done < <(find * -maxdepth 1 ! -name '*[!0-9]*' -type d -printf '%p\n' | sort -r -t '\0' -n | awk -F '\0' '{print $1}' | head -n 5)
}
_new() {
  latest=$(find * -maxdepth 1 ! -name '*[!0-9]*' -type d -printf '%p\n' | sort -t '\0' -n | awk -F '\0' '{print $1}' | tail -n1)
  ((latest++))

  datestring=$(date "+%A, %d %B %Y. %T%Z")

  read -r -p $'\e[33mZet title\e[0m: ' title

  [[ -z $title ]] && echo -e "\e[31mPlease provide a title for the zet!\e[0,:." && exit 1

  filepath="$directory/$latest/README.md"

  mkdir -p "$(dirname "$filepath")"

  touch "$filepath"
  {
    echo "# $title"
    echo -en "\n"
    echo "$datestring"
    echo -en "\n\n"
  } >>"$filepath"

  twindow "$filepath" "" "$EDITOR -c 'normal! G' $filepath" "open"
}

declare CMD="$1"
shift
for c in "${commands[@]}"; do
  [[ $c == "$CMD" ]] && "_$c" "$@" && exit $?
done
